PROPERTY_MAP = {
"_id": "_id",
"Product.Brand": "Product_Brand",
"Product.Family": "Product_Family",
"Product.Series": "Product_Series",
"Product.Model Name": "Product_Model_Name",
"Product.Target Market": "Product_Target_Market",
"Product.Model": "Product_Model",
"Product.Category": "Product_Category",
"Design.Body.Colors": "Design_Body_Colors",
"Design.Body.Style": "Design_Body_Style",
"Design.Body.Width (Longer Side)": "Design_Body_Width_Longer_Side_",
"Design.Body.Weight": "Design_Body_Weight",
"Design.Body.Height (Shorter Side)": "Design_Body_Height_Shorter_Side_",
"Design.Body.Thickness": "Design_Body_Thickness",
"Design.Body.Width (Longer Side)_mm": "Design_Body_Width_Longer_Side__mm",
"Design.Body.Height (Shorter Side)_mm": "Design_Body_Height_Shorter_Side__mm",
"Design.Body.Weight_g": "Design_Body_Weight_g",
"Design.Body.Thickness_mm": "Design_Body_Thickness_mm",
"Design.Touchpad.Pointing Device": "Design_Touchpad_Pointing_Device",
"Design.Keyboard.Model": "Design_Keyboard_Model",
"Design.Keyboard.Additional Features": "Design_Keyboard_Additional_Features",
"No.Touchscreen": "No_Touchscreen",
"No.ECC": "No_ECC",
"No.Dedicated Card": "No_Dedicated_Card",
"No.Numeric Keypad": "No_Numeric_Keypad",
"Display.Resolution (H x W)": "Display_Resolution_H_x_W_",
"Display.Definition": "Display_Definition",
"Display.Technology": "Display_Technology",
"Display.Brightness": "Display_Brightness",
"Display.Type": "Display_Type",
"Display.Additional Features": "Display_Additional_Features",
"Display.Diagonal": "Display_Diagonal",
"Inside.CPU.Generation": "Inside_CPU_Generation",
"Inside.CPU.Number of Cores": "Inside_CPU_Number_of_Cores",
"Inside.CPU.Clock Speed": "Inside_CPU_Clock_Speed",
"Inside.CPU.Family": "Inside_CPU_Family",
"Inside.CPU.Model": "Inside_CPU_Model",
"Inside.CPU.Number of Threads": "Inside_CPU_Number_of_Threads",
"Inside.CPU.Cache": "Inside_CPU_Cache",
"Inside.CPU.Maximum Frequency": "Inside_CPU_Maximum_Frequency",
"Inside.CPU.Brand": "Inside_CPU_Brand",
"Inside.RAM.Capacity": "Inside_RAM_Capacity",
"Inside.RAM.Type": "Inside_RAM_Type",
"Inside.RAM.Clock Speed": "Inside_RAM_Clock_Speed",
"Inside.GPU.Integrated Card Brand": "Inside_GPU_Integrated_Card_Brand",
"Inside.GPU.Dedicated Card Model": "Inside_GPU_Dedicated_Card_Model",
"Inside.GPU.Integrated Card Model": "Inside_GPU_Integrated_Card_Model",
"Inside.GPU.Integrated Card Family": "Inside_GPU_Integrated_Card_Family",
"Inside.SSD.Total SSD Capacity": "Inside_SSD_Total_SSD_Capacity",
"Inside.SSD.Storage Type": "Inside_SSD_Storage_Type",
"Inside.Wireless.WiFi Adapter": "Inside_Wireless_WiFi_Adapter",
"Inside.Wireless.WiFi Standards": "Inside_Wireless_WiFi_Standards",
"Inside.Wireless.Bluetooth Version": "Inside_Wireless_Bluetooth_Version",
"Inside.Ports.Number of HDMI Ports": "Inside_Ports_Number_of_HDMI_Ports",
"Inside.Ports.Number of Ethernet LAN (RJ-45) Ports": "Inside_Ports_Number_of_Ethernet_LAN_RJ-45_Ports",
"Inside.Ports.HDMI Version": "Inside_Ports_HDMI_Version",
"Inside.Ports.Number of Thunderbolt 4 Ports": "Inside_Ports_Number_of_Thunderbolt_4_Ports",
"Inside.Ports.Number of USB 3,2 Gen 1 Type A Ports": "Inside_Ports_Number_of_USB_3,2_Gen_1_Type_A_Ports",
"Inside.Ports.Additional Features": "Inside_Ports_Additional_Features",
"Inside.Software.Operating System Version": "Inside_Software_Operating_System_Version",
"Inside.Battery.Weight": "Inside_Battery_Weight",
"Inside.Battery.Type": "Inside_Battery_Type",
"Inside.Battery.Capacity (mAh)": "Inside_Battery_Capacity_mAh_",
"Inside.Power.Power": "Inside_Power_Power",
"Inside.Power.Frequency": "Inside_Power_Frequency",
"Inside.Power.Voltage": "Inside_Power_Voltage",
"Inside.Security.TPM (Trusted Platform Module) Version": "Inside_Security_TPM_Trusted_Platform_Module_Version",
"Inside.Security.Password Protection": "Inside_Security_Password_Protection",
"Inside.Security.Tools": "Inside_Security_Tools",
"Inside.Security.Additional Features": "Inside_Security_Additional_Features",
"Camera.Front Camera.Definition": "Camera_Front_Camera_Definition",
"Camera.Front Camera.Additional Features": "Camera_Front_Camera_Additional_Features",


}